"""
Catalog of ~200 workforce data sources with metadata and search.
Each entry maps to a source ID used by the connector layer.
"""

from dataclasses import dataclass, field
from typing import Optional
import re

SOURCES = [
    # ── BLS ──────────────────────────────────────────────────────────────────
    {
        "id": "bls_ces",
        "name": "Current Employment Statistics (CES)",
        "provider": "BLS",
        "section": "US Bureau of Labor Statistics",
        "description": "Monthly payroll employment, hours, and earnings for ~670,000 worksites by industry. The backbone of the monthly jobs report.",
        "topics": ["employment", "wages", "hours", "industry", "payroll", "jobs report"],
        "geography": ["national", "state", "metro"],
        "frequency": "monthly",
        "connector": "bls",
        "series_prefix": "CE",
        "url": "https://www.bls.gov/ces/",
        "free": True,
        "key_required": True,
    },
    {
        "id": "bls_cps",
        "name": "Current Population Survey (CPS)",
        "provider": "BLS / Census Bureau",
        "section": "US Bureau of Labor Statistics",
        "description": "Monthly household survey (~60,000 households) producing unemployment rate, labor force participation, demographics, part-time status, telework, union membership.",
        "topics": ["unemployment", "labor force participation", "demographics", "telework", "remote work", "union", "part-time", "contingent work"],
        "geography": ["national", "state"],
        "frequency": "monthly",
        "connector": "bls",
        "series_prefix": "LN",
        "url": "https://www.bls.gov/cps/",
        "free": True,
        "key_required": True,
    },
    {
        "id": "bls_jolts",
        "name": "Job Openings and Labor Turnover Survey (JOLTS)",
        "provider": "BLS",
        "section": "US Bureau of Labor Statistics",
        "description": "Monthly data on job openings, hires, and separations (quits, layoffs, discharges) by industry and region.",
        "topics": ["job openings", "hires", "quits", "layoffs", "separations", "turnover", "labor demand"],
        "geography": ["national", "state"],
        "frequency": "monthly",
        "connector": "bls",
        "series_prefix": "JT",
        "url": "https://www.bls.gov/jlt/",
        "free": True,
        "key_required": True,
    },
    {
        "id": "bls_qcew",
        "name": "Quarterly Census of Employment and Wages (QCEW)",
        "provider": "BLS",
        "section": "US Bureau of Labor Statistics",
        "description": "Near-census of employment and wages from 11.8M establishments covered by unemployment insurance, by county, MSA, state, and nationally at 6-digit NAICS.",
        "topics": ["employment", "wages", "establishment", "industry", "county", "payroll"],
        "geography": ["national", "state", "county", "metro"],
        "frequency": "quarterly",
        "connector": "bls",
        "series_prefix": "EN",
        "url": "https://www.bls.gov/cew/",
        "free": True,
        "key_required": True,
    },
    {
        "id": "bls_oews",
        "name": "Occupational Employment and Wage Statistics (OEWS)",
        "provider": "BLS",
        "section": "US Bureau of Labor Statistics",
        "description": "Semiannual employment and wage estimates for 800+ occupations at national, state, and metro-area levels.",
        "topics": ["occupation", "wages", "salary", "employment", "SOC", "skills"],
        "geography": ["national", "state", "metro"],
        "frequency": "semiannual",
        "connector": "bls",
        "series_prefix": "OE",
        "url": "https://www.bls.gov/oes/",
        "free": True,
        "key_required": True,
    },
    {
        "id": "bls_atus",
        "name": "American Time Use Survey (ATUS)",
        "provider": "BLS",
        "section": "US Bureau of Labor Statistics",
        "description": "Annual survey measuring how Americans spend their time — work, childcare, commuting, leisure. ~2,000 respondents/year. Microdata available.",
        "topics": ["time use", "work hours", "commuting", "childcare", "leisure", "work-life balance"],
        "geography": ["national"],
        "frequency": "annual",
        "connector": "bls",
        "series_prefix": "TU",
        "url": "https://www.bls.gov/tus/",
        "free": True,
        "key_required": True,
    },
    {
        "id": "bls_eci",
        "name": "Employment Cost Index (ECI)",
        "provider": "BLS",
        "section": "US Bureau of Labor Statistics",
        "description": "Quarterly measure of changes in labor costs (wages/salaries and benefits) by industry and occupation, controlling for compositional shifts.",
        "topics": ["labor costs", "wages", "benefits", "compensation", "inflation"],
        "geography": ["national"],
        "frequency": "quarterly",
        "connector": "fred",
        "fred_series": "ECIALLCIV",
        "url": "https://www.bls.gov/eci/",
        "free": True,
        "key_required": False,
    },
    {
        "id": "bls_ncs",
        "name": "National Compensation Survey / Employee Benefits Survey",
        "provider": "BLS",
        "section": "US Bureau of Labor Statistics",
        "description": "Quarterly employer costs per hour worked for wages and benefits; annual data on benefit access (retirement, healthcare, paid leave) by industry and establishment size.",
        "topics": ["benefits", "compensation", "healthcare", "retirement", "paid leave", "employer costs"],
        "geography": ["national"],
        "frequency": "quarterly",
        "connector": "bls",
        "series_prefix": "CC",
        "url": "https://www.bls.gov/ncs/",
        "free": True,
        "key_required": True,
    },
    {
        "id": "bls_bed",
        "name": "Business Employment Dynamics (BED)",
        "provider": "BLS",
        "section": "US Bureau of Labor Statistics",
        "description": "Quarterly gross job gains and losses, establishment births and deaths, expansions/contractions by industry, state, and establishment size.",
        "topics": ["job creation", "job destruction", "business dynamics", "establishment births", "layoffs"],
        "geography": ["national", "state"],
        "frequency": "quarterly",
        "connector": "bls",
        "series_prefix": "BD",
        "url": "https://www.bls.gov/bdm/",
        "free": True,
        "key_required": True,
    },
    {
        "id": "bls_productivity",
        "name": "Labor Productivity and Costs",
        "provider": "BLS",
        "section": "US Bureau of Labor Statistics",
        "description": "Quarterly output per hour and unit labor costs for the business sector, nonfarm business, and manufacturing.",
        "topics": ["productivity", "output", "unit labor costs", "efficiency"],
        "geography": ["national"],
        "frequency": "quarterly",
        "connector": "fred",
        "fred_series": "OPHNFB",
        "url": "https://www.bls.gov/lpc/",
        "free": True,
        "key_required": False,
    },
    {
        "id": "bls_iif",
        "name": "Injuries, Illnesses, and Fatalities (IIF/SOII/CFOI)",
        "provider": "BLS",
        "section": "US Bureau of Labor Statistics",
        "description": "Annual injury/illness rates from the Survey of Occupational Injuries and Illnesses (SOII) and fatal workplace injuries from the Census of Fatal Occupational Injuries (CFOI).",
        "topics": ["workplace safety", "injuries", "fatalities", "occupational health", "OSHA"],
        "geography": ["national", "state"],
        "frequency": "annual",
        "connector": "bls",
        "series_prefix": "IS",
        "url": "https://www.bls.gov/iif/",
        "free": True,
        "key_required": True,
    },
    {
        "id": "bls_nls",
        "name": "National Longitudinal Surveys (NLSY79 / NLSY97)",
        "provider": "BLS",
        "section": "US Bureau of Labor Statistics",
        "description": "Long-running panel surveys tracking employment histories, wages, education, training, fertility, and health for two birth cohorts (1957–64 and 1980–84).",
        "topics": ["longitudinal", "panel data", "employment history", "wages", "education", "career"],
        "geography": ["national"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://www.bls.gov/nls/",
        "free": True,
        "key_required": False,
        "notes": "Microdata downloadable via NLS Investigator tool.",
    },
    {
        "id": "bls_telework",
        "name": "BLS CPS Telework Data",
        "provider": "BLS",
        "section": "US Bureau of Labor Statistics",
        "description": "Monthly remote work rates from the CPS since October 2022, by industry, occupation, and demographics.",
        "topics": ["telework", "remote work", "work from home", "WFH"],
        "geography": ["national"],
        "frequency": "monthly",
        "connector": "bls",
        "series_prefix": "LN",
        "url": "https://www.bls.gov/cps/telework.htm",
        "free": True,
        "key_required": True,
    },

    # ── Census ────────────────────────────────────────────────────────────────
    {
        "id": "census_acs",
        "name": "American Community Survey (ACS)",
        "provider": "Census Bureau",
        "section": "US Census Bureau",
        "description": "Annual survey of ~3.5M households: employment, occupation, industry, income, commuting, work-from-home, education, poverty, health insurance. 1-year and 5-year estimates.",
        "topics": ["employment", "occupation", "income", "commuting", "work from home", "education", "poverty", "demographics"],
        "geography": ["national", "state", "county", "metro", "tract"],
        "frequency": "annual",
        "connector": "census",
        "dataset": "acs/acs1",
        "url": "https://www.census.gov/programs-surveys/acs",
        "free": True,
        "key_required": True,
    },
    {
        "id": "census_lehd_qwi",
        "name": "LEHD Quarterly Workforce Indicators (QWI)",
        "provider": "Census Bureau",
        "section": "US Census Bureau",
        "description": "Linked employer-employee data: quarterly employment, hires, separations, earnings, job creation/destruction by industry, geography, demographics, education, and firm age/size.",
        "topics": ["employment", "hires", "separations", "earnings", "firm size", "firm age", "worker demographics"],
        "geography": ["national", "state", "county", "metro"],
        "frequency": "quarterly",
        "connector": "census",
        "dataset": "timeseries/qwi/sa",
        "url": "https://lehd.ces.census.gov/",
        "free": True,
        "key_required": True,
    },
    {
        "id": "census_lodes",
        "name": "LEHD Origin-Destination (LODES) / OnTheMap",
        "provider": "Census Bureau",
        "section": "US Census Bureau",
        "description": "Residence-to-workplace commuting flows at the census block level for all 50 states.",
        "topics": ["commuting", "origin-destination", "workplace location", "residence"],
        "geography": ["national", "state", "county", "block"],
        "frequency": "annual",
        "connector": "census",
        "dataset": "lodes",
        "url": "https://lehd.ces.census.gov/",
        "free": True,
        "key_required": False,
        "notes": "Bulk download only; no API endpoint.",
    },
    {
        "id": "census_cbp",
        "name": "County Business Patterns (CBP)",
        "provider": "Census Bureau",
        "section": "US Census Bureau",
        "description": "Annual establishments, employment, and payroll by industry (NAICS) for every US county and ZIP code.",
        "topics": ["establishment", "employment", "payroll", "industry", "county", "ZIP code"],
        "geography": ["national", "state", "county", "ZIP"],
        "frequency": "annual",
        "connector": "census",
        "dataset": "cbp",
        "url": "https://www.census.gov/programs-surveys/cbp.html",
        "free": True,
        "key_required": True,
    },
    {
        "id": "census_susb",
        "name": "Statistics of US Businesses (SUSB)",
        "provider": "Census Bureau",
        "section": "US Census Bureau",
        "description": "Annual data on firms and establishments by employment size class, industry, and geography.",
        "topics": ["firm size", "establishment", "employment", "small business", "industry"],
        "geography": ["national", "state"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://www.census.gov/programs-surveys/susb.html",
        "free": True,
        "key_required": False,
    },
    {
        "id": "census_nonemployer",
        "name": "Nonemployer Statistics (NES)",
        "provider": "Census Bureau",
        "section": "US Census Bureau",
        "description": "Annual data on businesses with no paid employees (sole proprietors, self-employed) by industry and geography. Key for gig economy research.",
        "topics": ["self-employment", "gig economy", "freelance", "sole proprietor", "independent contractor"],
        "geography": ["national", "state", "county"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://www.census.gov/programs-surveys/nonemployer-statistics.html",
        "free": True,
        "key_required": False,
    },
    {
        "id": "census_sipp",
        "name": "Survey of Income and Program Participation (SIPP)",
        "provider": "Census Bureau",
        "section": "US Census Bureau",
        "description": "Longitudinal panel tracking income, employment, program participation, health insurance, assets, and family dynamics over ~4 years. ~50,000 households.",
        "topics": ["longitudinal", "income", "employment", "benefits", "health insurance", "poverty", "panel data"],
        "geography": ["national"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://www.census.gov/programs-surveys/sipp.html",
        "free": True,
        "key_required": False,
        "notes": "Public-use microdata available for download.",
    },
    {
        "id": "census_abs",
        "name": "Annual Business Survey (ABS)",
        "provider": "Census Bureau / NCSES",
        "section": "US Census Bureau",
        "description": "Annual survey of ~850,000 firms: innovation, R&D, technology adoption (including AI/robotics), business owner demographics.",
        "topics": ["innovation", "R&D", "technology", "AI adoption", "business owner", "firm characteristics"],
        "geography": ["national", "state"],
        "frequency": "annual",
        "connector": "census",
        "dataset": "abscs",
        "url": "https://www.census.gov/programs-surveys/abs.html",
        "free": True,
        "key_required": True,
    },
    {
        "id": "census_pulse",
        "name": "Household Pulse Survey",
        "provider": "Census Bureau",
        "section": "US Census Bureau",
        "description": "Rapid-response experimental survey tracking employment status, telework, childcare, food security, housing, and mental health. Launched during COVID, now periodic.",
        "topics": ["employment", "telework", "remote work", "childcare", "food security", "mental health", "COVID"],
        "geography": ["national", "state"],
        "frequency": "periodic",
        "connector": "external",
        "url": "https://www.census.gov/programs-surveys/household-pulse-survey.html",
        "free": True,
        "key_required": False,
    },

    # ── FRED ──────────────────────────────────────────────────────────────────
    {
        "id": "fred_main",
        "name": "FRED (Federal Reserve Economic Data)",
        "provider": "Federal Reserve Bank of St. Louis",
        "section": "Federal Reserve",
        "description": "Aggregator of 816,000+ time series from 118+ sources including virtually all BLS and Census labor data, plus financial and international data. Powerful API.",
        "topics": ["unemployment", "employment", "wages", "inflation", "GDP", "productivity", "interest rates", "labor force"],
        "geography": ["national", "state", "metro", "county"],
        "frequency": "varies",
        "connector": "fred",
        "url": "https://fred.stlouisfed.org/",
        "free": True,
        "key_required": True,
        "notes": "Single best API for macro time series. Covers most BLS + Census series.",
    },
    {
        "id": "fred_wage_tracker",
        "name": "Atlanta Fed Wage Growth Tracker",
        "provider": "Federal Reserve Bank of Atlanta",
        "section": "Federal Reserve",
        "description": "Monthly individual nominal wage growth from CPS microdata — median 12-month wage change by job-switchers/stayers, industry, demographics, and wage quartile.",
        "topics": ["wages", "wage growth", "job switchers", "stayers", "income", "compensation"],
        "geography": ["national"],
        "frequency": "monthly",
        "connector": "fred",
        "fred_series": "FEDMINNFRWAGE",
        "url": "https://www.atlantafed.org/chcs/wage-growth-tracker",
        "free": True,
        "key_required": False,
    },

    # ── DOL ──────────────────────────────────────────────────────────────────
    {
        "id": "dol_onet",
        "name": "O*NET (Occupational Information Network)",
        "provider": "DOL / ETA",
        "section": "US Department of Labor",
        "description": "Database of 923 occupations with standardized descriptors: tasks, skills, abilities, knowledge, work activities, work context, work values, interests, and technology used.",
        "topics": ["occupation", "skills", "tasks", "abilities", "knowledge", "work activities", "automation", "AI exposure", "SOC"],
        "geography": ["national"],
        "frequency": "quarterly",
        "connector": "onet",
        "url": "https://www.onetonline.org/",
        "free": True,
        "key_required": False,
        "notes": "REST API available. Updated ~quarterly. 923 occupations.",
    },
    {
        "id": "dol_flc",
        "name": "Foreign Labor Certification Disclosure Data",
        "provider": "DOL / ETA",
        "section": "US Department of Labor",
        "description": "Quarterly case-level data on H-1B, PERM, H-2A, H-2B visa applications — employer name, job title, wage offered, worksite, case status.",
        "topics": ["H-1B", "immigration", "visa", "foreign workers", "employer", "wages"],
        "geography": ["national", "state", "metro"],
        "frequency": "quarterly",
        "connector": "dol",
        "url": "https://www.dol.gov/agencies/eta/foreign-labor/performance",
        "free": True,
        "key_required": False,
    },
    {
        "id": "dol_whd",
        "name": "Wage and Hour Division Enforcement Data",
        "provider": "DOL WHD",
        "section": "US Department of Labor",
        "description": "FLSA, FMLA, and other wage-law enforcement actions — employer name, violations, back wages assessed, industry, geography.",
        "topics": ["enforcement", "wage theft", "FLSA", "FMLA", "violations", "back wages"],
        "geography": ["national", "state"],
        "frequency": "continuous",
        "connector": "dol",
        "url": "https://enforcedata.dol.gov/views/data_summary.php",
        "free": True,
        "key_required": False,
    },
    {
        "id": "dol_osha",
        "name": "OSHA Inspection and Enforcement Data",
        "provider": "DOL / OSHA",
        "section": "US Department of Labor",
        "description": "3M+ inspections since 1972: inspection detail, violations, penalties, injury/fatality data. Severe Injury Reports. ITA data (Forms 300A, 300, 301).",
        "topics": ["workplace safety", "OSHA", "inspections", "violations", "penalties", "injuries", "fatalities"],
        "geography": ["national", "state"],
        "frequency": "continuous",
        "connector": "dol",
        "url": "https://www.osha.gov/data",
        "free": True,
        "key_required": False,
    },
    {
        "id": "dol_ui",
        "name": "Unemployment Insurance (UI) Claims",
        "provider": "DOL / ETA",
        "section": "US Department of Labor",
        "description": "Weekly initial and continued UI claims by state. One of the most timely labor market indicators available.",
        "topics": ["unemployment", "UI claims", "layoffs", "initial claims", "continued claims"],
        "geography": ["national", "state"],
        "frequency": "weekly",
        "connector": "fred",
        "fred_series": "ICSA",
        "url": "https://oui.doleta.gov/unemploy/claims.asp",
        "free": True,
        "key_required": False,
    },
    {
        "id": "dol_wioa",
        "name": "WIOA Performance Data",
        "provider": "DOL / ETA",
        "section": "US Department of Labor",
        "description": "Annual outcomes of federally funded workforce training programs — participants served, employment rates, earnings gains, credential attainment.",
        "topics": ["workforce training", "employment outcomes", "earnings", "credentials", "upskilling"],
        "geography": ["national", "state"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://www.dol.gov/agencies/eta/performance",
        "free": True,
        "key_required": False,
    },

    # ── Other Federal ─────────────────────────────────────────────────────────
    {
        "id": "fed_scf",
        "name": "Survey of Consumer Finances (SCF)",
        "provider": "Federal Reserve Board",
        "section": "Other US Federal Agencies",
        "description": "Triennial survey of ~6,500 families covering income, employment, pensions, net worth, and financial behavior by detailed demographics.",
        "topics": ["income", "wealth", "pensions", "net worth", "retirement", "financial behavior"],
        "geography": ["national"],
        "frequency": "triennial",
        "connector": "external",
        "url": "https://www.federalreserve.gov/econres/scfindex.htm",
        "free": True,
        "key_required": False,
    },
    {
        "id": "fed_shed",
        "name": "Survey of Household Economics and Decisionmaking (SHED)",
        "provider": "Federal Reserve Board",
        "section": "Other US Federal Agencies",
        "description": "Annual survey (~11,000 adults) on economic well-being, employment, gig work, financial fragility, education debt, and retirement preparedness.",
        "topics": ["economic well-being", "gig work", "financial fragility", "retirement", "student debt"],
        "geography": ["national"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://www.federalreserve.gov/consumerscommunities/shed.htm",
        "free": True,
        "key_required": False,
    },
    {
        "id": "bea_main",
        "name": "Bureau of Economic Analysis (BEA)",
        "provider": "BEA / Commerce Department",
        "section": "Other US Federal Agencies",
        "description": "GDP by industry, compensation of employees, personal income by state/county/metro, regional price parities, and input-output tables.",
        "topics": ["GDP", "compensation", "income", "productivity", "industry output", "regional economics"],
        "geography": ["national", "state", "county", "metro"],
        "frequency": "quarterly",
        "connector": "fred",
        "fred_series": "GDP",
        "url": "https://www.bea.gov/",
        "free": True,
        "key_required": False,
    },
    {
        "id": "irs_soi",
        "name": "IRS Statistics of Income (SOI)",
        "provider": "IRS",
        "section": "Other US Federal Agencies",
        "description": "Aggregated tax-return data: individual income by ZIP code, sole proprietorship data, 1099-NEC/K filings (gig income), migration data, employee benefit plan statistics.",
        "topics": ["income", "gig economy", "self-employment", "1099", "migration", "tax", "sole proprietor"],
        "geography": ["national", "state", "county", "ZIP"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://www.irs.gov/statistics",
        "free": True,
        "key_required": False,
    },
    {
        "id": "opm_fwd",
        "name": "Federal Workforce Data (FWD / FedScope)",
        "provider": "OPM",
        "section": "Other US Federal Agencies",
        "description": "Comprehensive data on 2.1M federal civilian workforce: employment levels, hiring, separations, pay grades, occupations, demographics, agencies, telework. Monthly updates back to FY2005.",
        "topics": ["federal workforce", "government employment", "pay grades", "telework", "agencies"],
        "geography": ["national", "state"],
        "frequency": "monthly",
        "connector": "external",
        "url": "https://data.opm.gov",
        "free": True,
        "key_required": False,
    },
    {
        "id": "eeoc_eeo1",
        "name": "EEO-1 Component 1 Data",
        "provider": "EEOC",
        "section": "Other US Federal Agencies",
        "description": "Employer-reported workforce demographic data (race/ethnicity/sex by job category) for private employers with 100+ employees.",
        "topics": ["diversity", "demographics", "race", "ethnicity", "gender", "EEO", "equity"],
        "geography": ["national"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://www.eeoc.gov/data/eeo-1-data-collections",
        "free": True,
        "key_required": False,
    },
    {
        "id": "eeoc_charges",
        "name": "EEOC Charge Statistics",
        "provider": "EEOC",
        "section": "Other US Federal Agencies",
        "description": "Annual statistics on discrimination charges filed (by basis, issue, industry), resolutions, and monetary benefits.",
        "topics": ["discrimination", "harassment", "EEOC", "enforcement", "civil rights"],
        "geography": ["national"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://www.eeoc.gov/data/enforcement-and-litigation-statistics",
        "free": True,
        "key_required": False,
    },
    {
        "id": "uscis_h1b",
        "name": "USCIS H-1B Employer Data Hub",
        "provider": "DHS / USCIS",
        "section": "Other US Federal Agencies",
        "description": "H-1B petitions by employer, NAICS code, and wage level.",
        "topics": ["H-1B", "immigration", "visa", "skilled workers", "employer", "tech"],
        "geography": ["national", "state"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://www.uscis.gov/tools/reports-and-studies",
        "free": True,
        "key_required": False,
    },
    {
        "id": "sec_edgar",
        "name": "SEC EDGAR Human Capital Disclosures",
        "provider": "SEC",
        "section": "Financial & Corporate Disclosures",
        "description": "Public company 10-K filings with human capital disclosures (headcount, diversity, turnover, benefits since Nov 2020), proxy statements with executive compensation, 8-K layoff filings.",
        "topics": ["headcount", "executive compensation", "diversity", "layoffs", "turnover", "benefits", "public companies"],
        "geography": ["national", "global"],
        "frequency": "annual",
        "connector": "sec",
        "url": "https://www.sec.gov/edgar/searchedgar/companysearch",
        "free": True,
        "key_required": False,
    },
    {
        "id": "form5500",
        "name": "Form 5500 Pension/Benefits Plan Data",
        "provider": "DOL / EBSA",
        "section": "Financial & Corporate Disclosures",
        "description": "Annual filings by every private employer-sponsored benefit plan (pension, 401k, health): plan assets, participants, contributions, expenses. Millions of filings.",
        "topics": ["pension", "401k", "retirement", "health insurance", "benefits", "employer-sponsored"],
        "geography": ["national"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://www.dol.gov/agencies/ebsa/about-ebsa/our-activities/public-disclosure/foia/form-5500-datasets",
        "free": True,
        "key_required": False,
    },
    {
        "id": "layoffs_fyi",
        "name": "Layoffs.fyi",
        "provider": "Layoffs.fyi",
        "section": "Financial & Corporate Disclosures",
        "description": "Crowdsourced tracker of tech/startup layoffs since 2020 — company, headcount, date, percentage of workforce.",
        "topics": ["layoffs", "tech", "startups", "headcount", "reductions"],
        "geography": ["global"],
        "frequency": "continuous",
        "connector": "external",
        "url": "https://layoffs.fyi/",
        "free": True,
        "key_required": False,
    },

    # ── Academic ──────────────────────────────────────────────────────────────
    {
        "id": "psid",
        "name": "Panel Study of Income Dynamics (PSID)",
        "provider": "University of Michigan",
        "section": "Academic & Longitudinal",
        "description": "Longest-running household panel (since 1968), tracking ~5,000 families. Income, employment, hours, occupation, wealth, health, expenditures. Biennial.",
        "topics": ["longitudinal", "panel data", "income", "employment", "wealth", "intergenerational mobility"],
        "geography": ["national"],
        "frequency": "biennial",
        "connector": "external",
        "url": "https://psidonline.isr.umich.edu/",
        "free": True,
        "key_required": True,
        "notes": "Free registration required.",
    },
    {
        "id": "hrs",
        "name": "Health and Retirement Study (HRS)",
        "provider": "University of Michigan / NIA",
        "section": "Academic & Longitudinal",
        "description": "Biennial panel of 20,000+ Americans aged 50+ covering employment/retirement transitions, pensions, health, disability, cognition, and wealth.",
        "topics": ["retirement", "older workers", "health", "disability", "pensions", "aging workforce"],
        "geography": ["national"],
        "frequency": "biennial",
        "connector": "external",
        "url": "https://hrs.isr.umich.edu/",
        "free": True,
        "key_required": True,
    },
    {
        "id": "gss",
        "name": "General Social Survey (GSS)",
        "provider": "NORC at University of Chicago",
        "section": "Academic & Longitudinal",
        "description": "Biennial national survey (since 1972) with modules on job satisfaction, work autonomy, workplace conditions, income, and class identification.",
        "topics": ["job satisfaction", "work conditions", "autonomy", "social attitudes", "class"],
        "geography": ["national"],
        "frequency": "biennial",
        "connector": "external",
        "url": "https://gss.norc.org/",
        "free": True,
        "key_required": False,
    },
    {
        "id": "ipums",
        "name": "IPUMS (Integrated Public Use Microdata Series)",
        "provider": "University of Minnesota",
        "section": "Academic & Longitudinal",
        "description": "Harmonized microdata from CPS (1962–present), ACS/Census (1850–present), ATUS, NHIS, and international censuses. Dramatically simplifies access to Census and BLS microdata.",
        "topics": ["microdata", "CPS", "ACS", "census", "harmonized", "historical"],
        "geography": ["national", "international"],
        "frequency": "varies",
        "connector": "external",
        "url": "https://www.ipums.org/",
        "free": True,
        "key_required": True,
    },
    {
        "id": "opportunity_insights",
        "name": "Opportunity Insights (Chetty et al.)",
        "provider": "Harvard University",
        "section": "Academic & Longitudinal",
        "description": "Neighborhood-level economic mobility data (Opportunity Atlas), real-time Economic Tracker (employment, spending, job postings by county), and social capital data.",
        "topics": ["economic mobility", "inequality", "neighborhood", "real-time", "employment tracker", "social capital"],
        "geography": ["national", "state", "county", "metro"],
        "frequency": "varies",
        "connector": "external",
        "url": "https://opportunityinsights.org/data/",
        "free": True,
        "key_required": False,
    },
    {
        "id": "wfh_research",
        "name": "WFH Research — Survey of Working Arrangements and Attitudes (SWAA)",
        "provider": "Stanford / University of Chicago",
        "section": "Academic & Longitudinal",
        "description": "Monthly survey data since May 2020 on remote work rates, employer plans, worker preferences, and productivity perceptions. Global survey (27+ countries) also available.",
        "topics": ["remote work", "work from home", "WFH", "hybrid", "employer plans", "worker preferences"],
        "geography": ["national", "global"],
        "frequency": "monthly",
        "connector": "external",
        "url": "https://wfhresearch.com/data/",
        "free": True,
        "key_required": False,
    },
    {
        "id": "epi_data",
        "name": "EPI State of Working America Data Library",
        "provider": "Economic Policy Institute",
        "section": "Think Tanks & Nonprofits",
        "description": "Downloadable time-series on wages, income, inequality, benefits, employment, hours, productivity, and poverty.",
        "topics": ["wages", "inequality", "income", "benefits", "employment", "poverty", "productivity"],
        "geography": ["national", "state"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://www.epi.org/data/",
        "free": True,
        "key_required": False,
    },
    {
        "id": "brookings_bpea",
        "name": "Brookings/BPEA Labor Market Indicators Dataset",
        "provider": "Brookings Institution",
        "section": "Think Tanks & Nonprofits",
        "description": "94 monthly labor market indicators from January 1960–February 2026. Released March 2026.",
        "topics": ["labor market", "indicators", "employment", "wages", "historical"],
        "geography": ["national"],
        "frequency": "monthly",
        "connector": "external",
        "url": "https://www.brookings.edu/bpea-articles/",
        "free": True,
        "key_required": False,
    },
    {
        "id": "pew_work",
        "name": "Pew Research Center — Work & Workplace Data",
        "provider": "Pew Research Center",
        "section": "Think Tanks & Nonprofits",
        "description": "Survey data on remote work attitudes, gig work, AI at work, and economic attitudes. Datasets downloadable for free.",
        "topics": ["remote work", "gig work", "AI at work", "worker attitudes", "economic attitudes"],
        "geography": ["national"],
        "frequency": "periodic",
        "connector": "external",
        "url": "https://www.pewresearch.org/datasets/",
        "free": True,
        "key_required": False,
    },
    {
        "id": "mit_living_wage",
        "name": "MIT Living Wage Calculator",
        "provider": "MIT",
        "section": "Think Tanks & Nonprofits",
        "description": "Living wage estimates for every US county and metro area by family composition, based on local cost of living.",
        "topics": ["living wage", "minimum wage", "cost of living", "poverty", "family", "county"],
        "geography": ["national", "state", "county", "metro"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://livingwage.mit.edu/",
        "free": True,
        "key_required": False,
    },

    # ── Private Sector ────────────────────────────────────────────────────────
    {
        "id": "adp_ner",
        "name": "ADP National Employment Report",
        "provider": "ADP / Stanford Digital Economy Lab",
        "section": "Private Sector Data",
        "description": "Monthly private-sector employment change and pay insights (median pay for stayers vs. switchers) from 26M+ employees across 500K+ companies.",
        "topics": ["employment", "wages", "pay", "job switchers", "stayers", "private sector"],
        "geography": ["national"],
        "frequency": "monthly",
        "connector": "external",
        "url": "https://adpemploymentreport.com/",
        "free": True,
        "key_required": False,
    },
    {
        "id": "revelio_rpls",
        "name": "Revelio Labs Public Labor Statistics (RPLS)",
        "provider": "Revelio Labs",
        "section": "Private Sector Data",
        "description": "Free monthly employment, job openings, hiring, attrition, and wages from 100M+ US professional profiles by SOC occupation and NAICS sector. Released day before BLS Jobs Friday.",
        "topics": ["employment", "job openings", "hiring", "attrition", "wages", "occupation", "industry"],
        "geography": ["national", "state"],
        "frequency": "monthly",
        "connector": "external",
        "url": "https://www.reveliolabs.com/public-labor-statistics/",
        "free": True,
        "key_required": False,
    },
    {
        "id": "indeed_hiring_lab",
        "name": "Indeed Hiring Lab — Job Postings Tracker",
        "provider": "Indeed",
        "section": "Private Sector Data",
        "description": "Daily job postings indexes (vs Feb 2020 baseline) at national, state, metro, and sector level — the timeliest public read on US labor demand, published as open CSVs (CC-BY-4.0).",
        "topics": ["job postings", "hiring", "labor demand", "real-time", "state", "metro", "sector"],
        "geography": ["national", "state", "metro"],
        "frequency": "daily",
        "connector": "indeed",
        "url": "https://github.com/hiring-lab/job_postings_tracker",
        "free": True,
        "key_required": False,
    },
    {
        "id": "indeed_ai_tracker",
        "name": "Indeed Hiring Lab — AI Tracker",
        "provider": "Indeed",
        "section": "Technology & AI",
        "description": "Share of job postings mentioning AI terms (7-day trailing average, daily frequency, monthly refresh) — the most direct public measure of AI demand in hiring. Open CSVs (CC-BY-4.0).",
        "topics": ["AI", "job postings", "AI hiring", "generative AI", "real-time", "future of work"],
        "geography": ["national", "international"],
        "frequency": "monthly",
        "connector": "indeed",
        "url": "https://github.com/hiring-lab/ai-tracker",
        "free": True,
        "key_required": False,
    },
    {
        "id": "linkedin_econ_graph",
        "name": "LinkedIn Economic Graph",
        "provider": "LinkedIn",
        "section": "Private Sector Data",
        "description": "Reports on hiring rates, skills demand, talent migration, industry transitions, and gender gaps from 1B+ member profiles.",
        "topics": ["hiring", "skills", "talent migration", "industry", "gender gap", "careers"],
        "geography": ["national", "global"],
        "frequency": "periodic",
        "connector": "external",
        "url": "https://economicgraph.linkedin.com/",
        "free": True,
        "key_required": False,
    },
    {
        "id": "glassdoor_research",
        "name": "Glassdoor Economic Research",
        "provider": "Glassdoor",
        "section": "Private Sector Data",
        "description": "Job market and salary trends derived from employer reviews, salary reports, and job listings.",
        "topics": ["salaries", "job satisfaction", "company reviews", "employer", "hiring"],
        "geography": ["national"],
        "frequency": "periodic",
        "connector": "external",
        "url": "https://www.glassdoor.com/research/",
        "free": True,
        "key_required": False,
    },
    {
        "id": "lightcast_skills",
        "name": "Lightcast Open Skills Library",
        "provider": "Lightcast",
        "section": "Private Sector Data",
        "description": "Open-source taxonomy of 33,000+ skills from hundreds of millions of job postings. Free Skills API and Titles API (75,000+ job titles).",
        "topics": ["skills", "job titles", "taxonomy", "job postings", "labor demand"],
        "geography": ["national"],
        "frequency": "continuous",
        "connector": "external",
        "url": "https://lightcast.io/open-skills",
        "free": True,
        "key_required": False,
    },
    {
        "id": "homebase_data",
        "name": "Homebase Main Street Health",
        "provider": "Homebase",
        "section": "Private Sector Data",
        "description": "Monthly small business employment trends (hours worked, wages, employees, businesses open) from 100,000+ local businesses — restaurants, retail, services.",
        "topics": ["small business", "hourly workers", "restaurant", "retail", "employment", "hours"],
        "geography": ["national"],
        "frequency": "monthly",
        "connector": "external",
        "url": "https://www.joinhomebase.com/data",
        "free": True,
        "key_required": False,
    },
    {
        "id": "stackoverflow_survey",
        "name": "Stack Overflow Developer Survey",
        "provider": "Stack Overflow",
        "section": "Private Sector Data",
        "description": "Annual survey of 65,000+ developers worldwide — salary, employment, tools, remote work, job satisfaction, education, demographics. Full dataset downloadable.",
        "topics": ["tech workers", "developer", "salary", "remote work", "tools", "job satisfaction"],
        "geography": ["global"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://survey.stackoverflow.co/",
        "free": True,
        "key_required": False,
    },
    {
        "id": "levels_fyi",
        "name": "Levels.fyi Compensation Data",
        "provider": "Levels.fyi",
        "section": "Private Sector Data",
        "description": "Crowdsourced compensation data for tech companies — base salary, stock, bonus by company, level, location, and role.",
        "topics": ["tech compensation", "salary", "equity", "bonus", "big tech", "levels"],
        "geography": ["national", "global"],
        "frequency": "continuous",
        "connector": "external",
        "url": "https://www.levels.fyi/",
        "free": True,
        "key_required": False,
    },
    {
        "id": "kastle_barometer",
        "name": "Kastle Back to Work Barometer",
        "provider": "Kastle Systems",
        "section": "Office Occupancy",
        "description": "Weekly office occupancy data for 10 major US metros based on keycard swipe data from 2,600+ buildings.",
        "topics": ["office occupancy", "return to office", "RTO", "hybrid work", "commercial real estate"],
        "geography": ["metro"],
        "frequency": "weekly",
        "connector": "external",
        "url": "https://www.kastle.com/safety-wellness/getting-america-back-to-work/",
        "free": True,
        "key_required": False,
    },

    # ── International ─────────────────────────────────────────────────────────
    {
        "id": "ilostat",
        "name": "ILOSTAT",
        "provider": "International Labour Organization",
        "section": "International",
        "description": "Global reference: 250M+ data points, 400+ indicators, 200+ countries — employment, unemployment, wages, working time, labor force participation, informality, child labor.",
        "topics": ["global", "international", "employment", "unemployment", "wages", "informality", "child labor"],
        "geography": ["global"],
        "frequency": "varies",
        "connector": "external",
        "url": "https://ilostat.ilo.org/",
        "free": True,
        "key_required": False,
        "notes": "API available.",
    },
    {
        "id": "oecd_employment",
        "name": "OECD Employment Database",
        "provider": "OECD",
        "section": "International",
        "description": "Harmonized data for 38 OECD countries on employment/unemployment rates, earnings, hours, labor costs, job quality, skills, unions, and employment protection legislation.",
        "topics": ["OECD", "international", "employment", "wages", "hours", "unions", "job quality"],
        "geography": ["global"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://www.oecd.org/en/data/datasets/oecd-employment-database.html",
        "free": True,
        "key_required": False,
    },
    {
        "id": "world_bank_wdi",
        "name": "World Bank World Development Indicators (WDI)",
        "provider": "World Bank",
        "section": "International",
        "description": "1,600+ indicators for 217 economies — labor force participation, employment by sector, unemployment, informal employment, GDP per worker.",
        "topics": ["global", "developing countries", "labor force", "informality", "GDP", "employment"],
        "geography": ["global"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://databank.worldbank.org/source/world-development-indicators",
        "free": True,
        "key_required": False,
        "notes": "API available.",
    },
    {
        "id": "eurostat_labour",
        "name": "Eurostat Labour Market Data",
        "provider": "Eurostat",
        "section": "International",
        "description": "EU/EEA-wide data from the Labour Force Survey, Structure of Earnings Survey, labour cost indices. Employment, unemployment, hours, wages, education, job quality.",
        "topics": ["EU", "Europe", "employment", "wages", "hours", "job quality", "labour force survey"],
        "geography": ["global"],
        "frequency": "varies",
        "connector": "external",
        "url": "https://ec.europa.eu/eurostat/web/labour-market",
        "free": True,
        "key_required": False,
    },
    {
        "id": "wid_inequality",
        "name": "World Inequality Database (WID)",
        "provider": "Paris School of Economics",
        "section": "International",
        "description": "Pre-tax and post-tax income and wealth inequality for 170+ countries with long time series. Includes labor income shares.",
        "topics": ["inequality", "income distribution", "wealth", "labor share", "Gini", "global"],
        "geography": ["global"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://wid.world/",
        "free": True,
        "key_required": False,
    },

    # ── Health & Benefits ─────────────────────────────────────────────────────
    {
        "id": "meps_insurance",
        "name": "Medical Expenditure Panel Survey (MEPS) — Employer Component",
        "provider": "AHRQ",
        "section": "Healthcare & Benefits",
        "description": "Annual employer-sponsored health insurance data: offer rates, premiums, cost-sharing, plan types by employer size, industry, and state.",
        "topics": ["health insurance", "employer benefits", "premiums", "cost-sharing", "employer-sponsored"],
        "geography": ["national", "state"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://meps.ahrq.gov/",
        "free": True,
        "key_required": False,
    },
    {
        "id": "kff_benefits",
        "name": "KFF Employer Health Benefits Survey",
        "provider": "Kaiser Family Foundation",
        "section": "Healthcare & Benefits",
        "description": "Annual survey on employer-sponsored insurance — premiums, cost sharing, plan types, and wellness programs.",
        "topics": ["health insurance", "employer benefits", "premiums", "wellness", "cost sharing"],
        "geography": ["national"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://www.kff.org/health-costs/report/employer-health-benefits-annual-survey/",
        "free": True,
        "key_required": False,
    },

    # ── Education & Skills ────────────────────────────────────────────────────
    {
        "id": "college_scorecard",
        "name": "College Scorecard",
        "provider": "Department of Education",
        "section": "Education & Skills",
        "description": "Institution- and field-of-study-level data on costs, graduation rates, student debt, and post-college earnings (linked to IRS data). API available.",
        "topics": ["college earnings", "return on education", "student debt", "graduation", "major", "field of study"],
        "geography": ["national"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://collegescorecard.ed.gov/data/",
        "free": True,
        "key_required": True,
        "notes": "API key available at collegescorecard.ed.gov.",
    },
    {
        "id": "ipeds",
        "name": "IPEDS (Integrated Postsecondary Education Data System)",
        "provider": "NCES / Department of Education",
        "section": "Education & Skills",
        "description": "Annual data from every Title IV institution: enrollment, completions, graduation rates, finances, faculty salaries, and institutional characteristics.",
        "topics": ["higher education", "enrollment", "graduation", "faculty", "completions", "college"],
        "geography": ["national", "state"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://nces.ed.gov/ipeds/",
        "free": True,
        "key_required": False,
    },
    {
        "id": "coursera_skills",
        "name": "Coursera Global Skills Report",
        "provider": "Coursera",
        "section": "Education & Skills",
        "description": "Annual report on skill proficiency by country, region, and domain (business, technology, data science).",
        "topics": ["skills", "training", "online learning", "technology skills", "global"],
        "geography": ["global"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://www.coursera.org/skills-reports/global",
        "free": True,
        "key_required": False,
    },

    # ── Gig Economy ───────────────────────────────────────────────────────────
    {
        "id": "mbo_independence",
        "name": "MBO Partners State of Independence",
        "provider": "MBO Partners",
        "section": "Gig Economy & Nonstandard Work",
        "description": "Annual report on 72M+ independent workers in the US — headcount, earnings, satisfaction, trends.",
        "topics": ["freelance", "independent contractors", "gig economy", "self-employment", "contingent work"],
        "geography": ["national"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://www.mbopartners.com/state-of-independence/",
        "free": True,
        "key_required": False,
    },
    {
        "id": "upwork_freelance",
        "name": "Upwork Freelance Forward",
        "provider": "Upwork",
        "section": "Gig Economy & Nonstandard Work",
        "description": "Annual study of the US freelance workforce — demographics, income, motivations, skill areas.",
        "topics": ["freelance", "gig economy", "remote work", "independent", "income"],
        "geography": ["national"],
        "frequency": "annual",
        "connector": "external",
        "url": "https://www.upwork.com/research/freelance-forward",
        "free": True,
        "key_required": False,
    },

    # ── Commuting & Real Estate ────────────────────────────────────────────────
    {
        "id": "nhts",
        "name": "National Household Travel Survey (NHTS)",
        "provider": "FHWA / DOT",
        "section": "Commuting & Transportation",
        "description": "Periodic survey on personal travel behavior including commute mode, distance, time, and telecommute frequency. Most recent: 2022.",
        "topics": ["commuting", "travel", "transit", "telecommute", "transportation mode"],
        "geography": ["national"],
        "frequency": "periodic",
        "connector": "external",
        "url": "https://nhts.ornl.gov/",
        "free": True,
        "key_required": False,
    },

    # ── Legal & Enforcement ───────────────────────────────────────────────────
    {
        "id": "nlrb_cases",
        "name": "NLRB Case Data",
        "provider": "NLRB",
        "section": "Legal & Regulatory",
        "description": "Searchable database of union election petitions, unfair labor practice charges, decisions, and outcomes.",
        "topics": ["unions", "collective bargaining", "labor relations", "NLRB", "unfair labor practices"],
        "geography": ["national"],
        "frequency": "continuous",
        "connector": "external",
        "url": "https://www.nlrb.gov/search/case",
        "free": True,
        "key_required": False,
    },
    {
        "id": "warn_layoffdata",
        "name": "WARN Act Notices (LayoffData.com)",
        "provider": "LayoffData.com",
        "section": "Legal & Regulatory",
        "description": "Standardized database of 81,000+ WARN Act notices from 49 states — employer name, location, employees affected, date.",
        "topics": ["layoffs", "plant closings", "mass layoffs", "WARN Act", "workforce reduction"],
        "geography": ["national", "state"],
        "frequency": "continuous",
        "connector": "external",
        "url": "https://layoffdata.com/",
        "free": True,
        "key_required": False,
    },

    # ── AI & Technology ────────────────────────────────────────────────────────
    {
        "id": "ai_exposure",
        "name": "AI/Automation Exposure Indices",
        "provider": "Various Researchers",
        "section": "Technology & AI",
        "description": "Occupation-level AI and automation exposure scores built on O*NET task data. Includes Frey & Osborne (Oxford), Felten/Raj/Seamans, Acemoglu & Restrepo, Eloundou et al. (OpenAI GPT exposure).",
        "topics": ["AI", "automation", "occupation exposure", "future of work", "robots", "GPT", "tasks"],
        "geography": ["national"],
        "frequency": "periodic",
        "connector": "external",
        "url": "https://www.oxfordmartin.ox.ac.uk/downloads/academic/The_Future_of_Employment.pdf",
        "free": True,
        "key_required": False,
    },
    {
        "id": "github_innovation",
        "name": "GitHub Innovation Graph",
        "provider": "GitHub",
        "section": "Technology & AI",
        "description": "Quarterly data on developer activity (repositories, pushes, developers) across 200+ countries.",
        "topics": ["developers", "software", "open source", "tech workforce", "coding"],
        "geography": ["global"],
        "frequency": "quarterly",
        "connector": "external",
        "url": "https://innovationgraph.github.com/",
        "free": True,
        "key_required": False,
    },
]


def search(query: str, section: Optional[str] = None, connector: Optional[str] = None) -> list[dict]:
    """
    Full-text search across source name, description, and topics.
    Optionally filter by section or connector type.
    Returns results sorted by relevance (number of matching terms).
    """
    query_lower = query.lower()
    terms = re.split(r"\s+", query_lower.strip())

    results = []
    for source in SOURCES:
        if section and source.get("section") != section:
            continue
        if connector and source.get("connector") != connector:
            continue

        searchable = " ".join([
            source.get("name", ""),
            source.get("description", ""),
            " ".join(source.get("topics", [])),
            source.get("provider", ""),
            source.get("section", ""),
        ]).lower()

        score = sum(1 for term in terms if term in searchable)
        if score > 0:
            results.append({**source, "_score": score})

    results.sort(key=lambda x: x["_score"], reverse=True)
    return results


def get_source(source_id: str) -> Optional[dict]:
    """Return a single source by its ID."""
    for s in SOURCES:
        if s["id"] == source_id:
            return s
    return None


def list_sections() -> list[str]:
    """Return all unique section names."""
    return sorted(set(s["section"] for s in SOURCES))


def list_connectors() -> list[str]:
    """Return all unique connector types."""
    return sorted(set(s["connector"] for s in SOURCES))


def list_topics() -> list[str]:
    """Return all unique topic tags, sorted alphabetically."""
    topics = set()
    for s in SOURCES:
        topics.update(s.get("topics", []))
    return sorted(topics)


def filter_sources(
    section: Optional[str] = None,
    connector: Optional[str] = None,
    free_only: bool = True,
    geography: Optional[str] = None,
    frequency: Optional[str] = None,
) -> list[dict]:
    """Filter the catalog by any combination of attributes."""
    results = []
    for source in SOURCES:
        if section and source.get("section") != section:
            continue
        if connector and source.get("connector") != connector:
            continue
        if free_only and not source.get("free", True):
            continue
        if geography and geography.lower() not in [g.lower() for g in source.get("geography", [])]:
            continue
        if frequency and source.get("frequency", "").lower() != frequency.lower():
            continue
        results.append(source)
    return results
